baseurl = "https://coutinholab.github.io/"
languageCode = "en-us"
theme = "terminal"
paginate = 5

[params]
  contentTypeName = "posts"
  themeColor = "blue"
  showMenuItems = 5
  fullWidthTheme = true
  centerTheme = true

[languages]
  [languages.en]
    title = "The Coutinho Lab"
    subtitle = ""
    keywords = ""
    copyright = "© 2022 The Coutinho Lab"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "CoutinhoLab"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "news"
        name = "News"
        url = "/news"
      [[languages.en.menu.main]]
        identifier = "resources"
        name = "Resources"
        url = "/resources"
      [[languages.en.menu.main]]
        identifier = "publications"
        name = "Publications"
        url = "/pubs"
      [[languages.en.menu.main]]
        identifier = "people"
        name = "People"
        url = "/people"
      [[languages.en.menu.main]]
        identifier = "research"
        name = "Research"
        url = "/research"